import math
from dataclasses import dataclass

from common import Point3, ColorRgb
from textures import Texture


@dataclass
class CheckerTexture(Texture):
    """
    Checker will generate a "checkerboard" texture.
    The checker `odd`/`even` properties can be to a constant texture or to some other
    procedural texture.

    A checkerboard texture can be generated by noticing that the sign of sine and cosine just
    alternates in a regular way. If we multiply trig functions in all three dimensions, the sign
    of that product forms a 3D checker pattern
    """
    odd: Texture
    even: Texture

    def value(self, u: float, v: float, p: Point3) -> ColorRgb:
        """
        returns the checkerboard color at the given u,v coordinate and point p
        """
        sines = math.sin(10.0 * p.x) * math.sin((10.0 * p.y)) * math.sin(10.0 * p.z)

        if sines < 0.0:
            return self.odd.value(u, v, p)
        else:
            return self.even.value(u, v, p)


